import { useState } from 'react';
import { submitConsultation, submitContact, submitTalent } from '../../services/api';

function FormShell({ title, intro, children, state }) { return <><section className="form-hero"><div><p className="eyebrow">Let's talk</p><h1>{title}</h1><p>{intro}</p></div></section><section className="band form-section"><div className="form-aside"><p className="eyebrow">Tell us enough to begin</p><p>We reply within one business day. Your information stays private and is only used to respond to your request.</p></div><div>{state.status && <div className="form-status success" role="status">{state.status}</div>}{state.error && <div className="form-status error" role="alert">{state.error}</div>}{children}</div></section></>; }
export function Field({ label, name, value, onChange, type = 'text', textarea, select, options = [], required }) { return <label className="field"><span>{label}{required && ' *'}</span>{textarea ? <textarea name={name} value={value} onChange={onChange} rows="4" required={required}/> : select ? <select name={name} value={value} onChange={onChange} required={required}><option value="">Select one</option>{options.map((option) => <option key={option}>{option}</option>)}</select> : <input name={name} type={type} value={value} onChange={onChange} required={required}/>}</label>; }
function Submit({ children, loading }) { return <button className="button form-submit" disabled={loading}>{loading ? 'Sending...' : children}<span aria-hidden="true">↗</span></button>; }
function useLeadForm(submitLead) { const [form, setForm] = useState({}); const [state, setState] = useState({}); const update = (event) => setForm({ ...form, [event.target.name]: event.target.value }); const submit = async (event) => { event.preventDefault(); setState({ loading: true }); try { const result = await submitLead({ ...form, consentGiven: true }); setState({ status: result.message }); setForm({}); } catch (error) { setState({ error: error.message }); } }; return { form, state, update, submit }; }
export function ContactForm() { const { form, state, update, submit } = useLeadForm(submitContact); return <FormShell title="Start with a good question." intro="Whether you have a clear brief or a knot to untangle, we would like to hear about it." state={state}><form onSubmit={submit} className="lead-form"><Field label="Your name" name="fullName" value={form.fullName || ''} onChange={update} required/><Field label="Email address" name="email" type="email" value={form.email || ''} onChange={update} required/><Field label="Company (optional)" name="company" value={form.company || ''} onChange={update}/><Field label="What can we help with?" name="service" value={form.service || ''} onChange={update} required select options={['Product engineering','Data intelligence','Education technology','Something else']}/><Field label="A little about the challenge" name="message" value={form.message || ''} onChange={update} textarea required/><Submit loading={state.loading}>Send inquiry</Submit></form></FormShell>; }
export function ConsultationForm() { const { form, state, update, submit } = useLeadForm(submitConsultation); return <FormShell title="Make learning work harder." intro="Tell us where your education initiative is headed. We will help you find the clearest next step." state={state}><form onSubmit={submit} className="lead-form"><Field label="Your name" name="fullName" value={form.fullName || ''} onChange={update} required/><Field label="Email address" name="email" type="email" value={form.email || ''} onChange={update} required/><Field label="Organization" name="company" value={form.company || ''} onChange={update}/><Field label="What are you looking for?" name="requirement" value={form.requirement || ''} onChange={update} required textarea/><Field label="Preferred date (optional)" name="preferredDate" type="date" value={form.preferredDate || ''} onChange={update}/><Submit loading={state.loading}>Request a consultation</Submit></form></FormShell>; }
export function TalentForm() { const { form, state, update, submit } = useLeadForm(submitTalent); return <FormShell title="Bring your particular talent." intro="We are always interested in meeting people who care about the quality of the work." state={state}><form onSubmit={submit} className="lead-form"><Field label="Your name" name="fullName" value={form.fullName || ''} onChange={update} required/><Field label="Email address" name="email" type="email" value={form.email || ''} onChange={update} required/><Field label="Phone (optional)" name="phone" value={form.phone || ''} onChange={update}/><Field label="Your key skills" name="skills" value={form.skills || ''} onChange={update} required textarea/><Field label="LinkedIn or portfolio (optional)" name="linkedinUrl" value={form.linkedinUrl || ''} onChange={update}/><Submit loading={state.loading}>Join the network</Submit></form></FormShell>; }
