import { Link } from 'react-router-dom';

export function Hero({ eyebrow, title, text, children }) {
  return <section className="hero"><div className="hero-copy"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p>{children}</div><div className="hero-aside"><span className="aside-number">01</span><span>Independent digital partner<br />for ambitious teams</span></div></section>;
}

export function ArrowLink({ to, children }) { return <Link className="arrow-link" to={to}>{children}<span aria-hidden="true">↗</span></Link>; }
export function RevealGrid({ items, kind = 'solution' }) { return <div className="reveal-grid">{items.map((item, index) => <article className="feature-item" key={item.slug}><span className="item-index">0{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p><ArrowLink to={`/${kind === 'solution' ? 'solutions' : 'industries'}/${item.slug}`}>Explore</ArrowLink></article>)}</div>; }
export function Listing({ title, eyebrow, text, items, kind }) { return <><Hero eyebrow={eyebrow} title={title} text={text}/><section className="band"><div className="list-header"><p className="eyebrow">Explore the practice</p><span>{items.length} areas</span></div><RevealGrid items={items} kind={kind}/></section></>; }
export function DetailPage({ collection, base, eyebrow }) { const item = collection.find((entry) => entry.slug === window.location.pathname.split('/').pop()); if (!item) return <NotFound />; return <><Hero eyebrow={`${eyebrow} / Detail`} title={item.title} text={item.text}><Link className="button" to="/contact">Discuss this with us <span aria-hidden="true">↗</span></Link></Hero><section className="band detail-body"><div><p className="eyebrow">What this includes</p><h2>Thoughtful work,<br />built to last.</h2></div><div className="detail-content">{item.points ? item.points.map((point) => <div className="detail-point" key={point}><span aria-hidden="true">+</span><p>{point}</p></div>) : <p>{item.text} We work alongside your team to turn the opportunity into a clear path forward, with the tools and confidence to keep going.</p>}<ArrowLink to={base}>Back to {eyebrow.toLowerCase()}</ArrowLink></div></section></>; }
export function NotFound() { return <section className="not-found"><p className="eyebrow">404 / Page not found</p><h1>That page took<br /><em>a different route.</em></h1><Link className="button" to="/">Return home <span aria-hidden="true">↗</span></Link></section>; }
