import { Link, useParams } from 'react-router-dom';
import { caseStudies, jobs, posts, solutions, industries } from '../data/siteData';
import { ButtonLink, Eyebrow, SectionHeading } from '../components/SiteShell';
import { ArrowLink, Hero, Listing, DetailPage, NotFound } from '../components/common/PagePrimitives';

export function Home() { return <><Hero eyebrow="Mylotic / Digital systems" title={<>Make the complex<br /><em>useful.</em></>} text="We partner with people building the future of work, learning, and everyday life. Strategy, design, and engineering in one considered practice."><ButtonLink to="/contact">Start a conversation</ButtonLink></Hero><section className="band introduction"><div className="statement"><Eyebrow>Our point of view</Eyebrow><h2>Good technology gives people more room to do their best thinking.</h2></div><div className="statement-detail"><p>We bring clarity to complicated challenges and momentum to ideas that matter. Every engagement is shaped around the people who will live with the result.</p><ArrowLink to="/company">How we work</ArrowLink></div></section><section className="band"><SectionHeading eyebrow="What we do" title="A focused practice for meaningful change" text="The right answer is rarely a single discipline. We bring the right mix together, at the right moment."/><div className="reveal-grid">{solutions.map((item, index) => <article className="feature-item" key={item.slug}><span className="item-index">0{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p><ArrowLink to={`/solutions/${item.slug}`}>Explore</ArrowLink></article>)}</div></section><section className="dark-band"><div className="dark-feature"><Eyebrow>Selected work</Eyebrow><h2>Small details.<br /><span>Large outcomes.</span></h2><p>See how we turn ambitious briefs into systems people actually want to use.</p><ButtonLink to="/work" secondary>View our work</ButtonLink></div></section><section className="band cta-band"><Eyebrow>Have a difficult problem?</Eyebrow><h2>Let's make something<br /><em>clearer.</em></h2><ButtonLink to="/contact">Talk to Mylotic</ButtonLink></section></>; }
export function Company() { return <><Hero eyebrow="Company / 01" title="We make progress feel possible." text="Mylotic is an independent technology company for organizations with something important to build."><ButtonLink to="/company/approach">Our approach</ButtonLink></Hero><section className="band split-section"><div><Eyebrow>Why Mylotic</Eyebrow><h2>Less theatre.<br />More traction.</h2></div><div className="prose"><p>We are a small, senior team that works across strategy, product design, and engineering. That means fewer handoffs, sharper decisions, and work that stays connected to the reason it exists.</p><p>We believe the best partnerships are candid, curious, and built for the long term. The work should make your team stronger, not more dependent.</p></div></section><section className="band"><SectionHeading eyebrow="Meet the people" title="A team with range and rigor"/><div className="people-row"><div className="person-card"><span>01</span><h3>Product minds</h3><p>Questions that reveal the work underneath the work.</p></div><div className="person-card"><span>02</span><h3>Technical depth</h3><p>Ambitious systems sturdy enough for real life.</p></div><div className="person-card"><span>03</span><h3>Human pace</h3><p>Space for insight, iteration, and good judgment.</p></div></div><div className="inline-links"><ArrowLink to="/company/leadership">Leadership</ArrowLink><ArrowLink to="/company/approach">Our approach</ArrowLink></div></section></>; }
export function Approach() { const steps=['Understand the real problem','Make the shape visible','Build for the next chapter','Measure what matters']; return <><Hero eyebrow="Company / Approach" title="A better way to move from idea to impact." text="We work in close loops: understand deeply, make deliberately, learn quickly, and leave your team with something stronger."><ButtonLink to="/contact">Bring us a challenge</ButtonLink></Hero><section className="band numbered-list">{steps.map((title,i)=><div className="number-row" key={title}><span>0{i+1}</span><h2>{title}</h2><p>{['We listen to your people, constraints, and ambitions before proposing an answer.','Prototypes turn abstract conversation into useful decisions everyone can see.','The best solution is resilient, accessible, and ready to evolve.','We agree on signals of progress, then keep learning after launch.'][i]}</p></div>)}</section></>; }
export function Leadership() { return <><Hero eyebrow="Company / Leadership" title="Senior attention, from first question to final detail." text="The people you meet are the people who shape the work. No layers between the brief and the outcome."/><section className="band leadership-grid"><div className="leader-feature"><div className="portrait portrait-olive">MR</div><Eyebrow>Founder / Strategy</Eyebrow><h2>Mylotic is built around useful ambition.</h2><p>Our leadership team brings together product, technology, and learning experience to make change practical.</p></div><div className="leader-note"><span>“</span><p>Clarity is not a constraint on ambition. It is what lets ambition travel further.</p></div></section></>; }
export const Solutions=()=> <Listing eyebrow="Solutions / 02" title="Build what the moment needs." text="Strategy, design, and engineering for teams taking a meaningful next step." items={solutions} kind="solution"/>;
export const Industries=()=> <Listing eyebrow="Industries / 03" title="Context changes everything." text="We learn the language of your world, then make technology feel native to it." items={industries} kind="industry"/>;
export function SolutionDetail(){return <DetailPage collection={solutions} base="/solutions" eyebrow="Solutions"/>} export function IndustryDetail(){return <DetailPage collection={industries} base="/industries" eyebrow="Industries"/>}
export function Work(){return <><Hero eyebrow="Work / 04" title="Proof is in the experience." text="We are preparing approved case studies for publication. Until then, the best place to begin is a conversation about your challenge."/><section className="band empty-state"><Eyebrow>Selected work</Eyebrow><h2>Approved case studies<br />will appear here.</h2><ArrowLink to="/contact">Start a conversation</ArrowLink></section></>}
export function WorkDetail(){const {slug}=useParams();const item=caseStudies.find((x)=>x.slug===slug);if(!item)return <NotFound/>;return <><Hero eyebrow="Work / Case study" title={item.title} text={item.text}/><section className="band split-section"><div><Eyebrow>The outcome</Eyebrow><h2>Made for the people inside the system.</h2></div><div className="prose"><p>We worked from the lived experience outward, creating a product that makes the important things easier to find, understand, and act on.</p><ArrowLink to="/contact">Start a similar conversation</ArrowLink></div></section></>}
export function Technology(){return <><Hero eyebrow="Technology / 05" title="Technology should disappear into the work." text="The stack matters. The people using it matter more."/><section className="band tech-layout"><div><Eyebrow>Our toolkit</Eyebrow><h2>Modern where it helps.<br />Quiet where it doesn't.</h2></div><div className="tech-list">{['Web platforms','Data & intelligence','Cloud foundations','Design systems','Responsible AI'].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>Purposeful choices, documented well, and built for your team.</p></div>)}</div></section></>}
export function Careers(){return <><Hero eyebrow="Careers / 06" title="Do the best work of your career." text="Join a small, ambitious team working on problems with a human shape."/><section className="band jobs-section"><SectionHeading eyebrow="Open roles" title="Find your next good challenge"/><div className="job-list">{jobs.map((job)=><Link className="job-row" key={job.slug} to={`/careers/${job.slug}`}><div><Eyebrow>{job.type} / {job.location}</Eyebrow><h2>{job.title}</h2></div><span aria-hidden="true">↗</span></Link>)}</div><div className="talent-invite"><p>Not seeing the right role?</p><ArrowLink to="/careers/talent">Share your talent</ArrowLink></div></section></>}
export function Blog(){const sectionNumber = '05'; return <><Hero eyebrow={`Insights / ${sectionNumber}`} title="Ideas for people making things matter." text="Notes from our practice on technology, learning, design, and the shape of progress."/><section className="band post-list">{posts.map((post,i)=><Link className="post-row" key={post.slug} to={`/blog/${post.slug}`}><span className="post-number">0{i+1}</span><div><Eyebrow>{post.category} / {post.date}</Eyebrow><h2>{post.title}</h2><p>{post.excerpt}</p></div><span aria-hidden="true">↗</span></Link>)}</section></>}
export function BlogDetail(){const {slug}=useParams();const post=posts.find((x)=>x.slug===slug);if(!post)return <NotFound/>;return <><Hero eyebrow={`Insights / ${post.category}`} title={post.title} text={post.excerpt}/><section className="band article"><Eyebrow>{post.date}</Eyebrow><p>There is a particular kind of progress that does not announce itself. It shows up as a clearer decision, a kinder workflow, or a person who can finally get on with the important thing.</p><p>That is the work we care about. Not technology for its own sake, but systems that make good intentions easier to act on.</p><ArrowLink to="/blog">Back to insights</ArrowLink></section></>}
export function Legal({title,label}){return <><Hero eyebrow={`Legal / ${label}`} title={title} text="Straightforward information about how Mylotic works with people and their information."/><section className="band legal-copy"><h2>Our commitment</h2><p>We believe trust is built through clarity. We collect only what is needed, use it for the purpose described, and take reasonable steps to protect it.</p><h3>Questions are welcome</h3><p>For questions, contact <a href="mailto:hello@mylotic.com">hello@mylotic.com</a>.</p></section></>}
